### PR TITLE
add aviator crate

### PR DESCRIPTION
**Pull request by wowluanoob**
i like this project so i would like to help

### CODE REVIEW

**Comment by wowluanoob** [comment]
Also you are not calculating steam 15% tax in the EV calculation part
currently its 
EV = items_EV - key_price
i propose you make it
EV = items_EV - key_price - (0.15 * items_EV)

**Comment by falkben** [comment]
Thank you for the patch.  Typically I add the source to the readme for each crate.  Also, I assume the drop rates on the other crates changed as well?

You are correct on the EV calculation part.  Should be straightforward to fix.

**Comment by wowluanoob** [comment]
No problem. I guess the drop rates are different too. Why do you add them
though? Is there something it calculates like BP efficiency or something?
So sad they ruined trading this little program is awesome

**Comment by falkben** [comment]
At some point I'd like to be able to calculate which crate to get (when they release a new crate, sometimes they offer a choice between random crate drop or new crate with key).

**Comment by wowluanoob** [comment]
https://support.playbattlegrounds.com/hc/en-us/articles/360003229514-What-is-inside-the-Equinox-Crate-

**Comment by wowluanoob** [comment]
and with aviator crate added

 Survivor: 5%
   Wanderer: 5%
   Biker: 10%
   Desperado: 2.5%
   Militia: 15%
   Fever: 2.5%
   Triumph: 10%
   Aviator: 20%
   Eguinox: 15%
   Raider: 15%

**Comment by wowluanoob** [comment]
also can you show where to edit for us and euro currency?

**Pull request merged**
